###############################################################################
# This is the NEWM Market Batcher v1 config file. The data is split between
# hardcoded values that should not be changed and batcher specific values that
# need to be updated. Follow the README for detailed directions.
###############################################################################

###############################################################################
# Update Values For Your Batcher
###############################################################################

# Batcher Information
batcher_address: ""
profit_address: ""

# Collat Wallet Information
collat_address: ""
collat_utxo: ""

# Network Information
# network: "--mainnet"
network: "--testnet-magic 1"

# Bin Paths; Need To be Absolute
cli_path: "/newm-batcher-v1/bin/cardano-cli"
oura_path: "/newm-batcher-v1/bin/oura"
ogmios_path: "/newm-batcher-v1/bin/ogmios"
aiken_path: "/newm-batcher-v1/bin/aiken"
addr_path: "/newm-batcher-v1/bin/cardano-address"

# File Paths; Needs To Be Absolute
socket_path: "/node.socket"
node_config_path: "/config.json"

# True Uses Ogmios For Tx Simulation; False Uses Aiken For Tx Simulation
use_ogmios: True

# Socket and Cardano CLI Information

# Docker - Do Not Use Yet
# socket_path: "/root/node/node.socket"
# cli_path: "/root/bin/cardano-cli"

###############################################################################
# Do Not Update Values Below
###############################################################################

# Oracle Feed Address
oracle_address: "addr_test1wzc86g4ym366hkaphryqqvaptwznqkmk2gdqz9930u534pcx58ahw"
oracle_policy: "362e3f869c98ce971ead0e2705c56df467ddd2aecb44f6f216c3e1d5"
oracle_asset: "4f7261636c6546656564"

# Sale & Queue & Vault Contract Addresses
sale_address: "addr_test1xzsc88ldzuf9y244ccgkaxvf5jgnyz94t5jtpl96ch0zndqyjgfjgmu4hmdkeeuwyh370gfs94rjz5vakqn8dvff2hcsnl3v4t"
queue_address: "addr_test1xrd2t4885kvekzcsufvf09sgerxcvnf9wcyww6fnnzfydgcyjgfjgmu4hmdkeeuwyh370gfs94rjz5vakqn8dvff2hcs0rl7u3"
vault_address: "addr_test1xrh0fqjh6y2u0ykzves422pu5h5kyfyzs2a7p5mpdsrky2qyjgfjgmu4hmdkeeuwyh370gfs94rjz5vakqn8dvff2hcsqv2372"

# Data Contract
data_address: "addr_test1wzy7gftt4c0685hzry0c4f9az9pyn06xcswfvv4a6qxh0sc4qahfl"
data_policy: "7d878696b149b529807aa01b8e20785e0a0d470c32c13f53f08a55e3"
data_asset: "44455633393337"

# Data, Sale, and Queue Contract Script Reference UTxOs
reference_address: "addr_test1vpdhs4kp98kyagc5zy098yrhxn5tsc7d4z4g8vd8d32ez4cq6r27z"

sale_ref_utxo: "6b19610151abde605dae5618437c6650b4ac293d2fbdda4b56af6fd3e250cfc7#1"
sale_lovelace: 41789760

queue_ref_utxo: "d17bcc20fc3b9119122824de6de270a60c87322e1aeae0ee86dc8640815a4833#1"
queue_lovelace: 57603150

vault_ref_utxo: "04fab56d0030f172256619d19449db1278ac579588328c5c58c73ba5831ece82#1"
vault_lovelace: 29458850

# The Newm Pointer Policy Id
pointer_policy: "b3bb4a860d05b5d06cc45636950a02b6dd6c729111f0df844e711d27"

# The Newm Batcher Policy Id
batcher_policy: "1ada24cd8e945b000a0b2846b80f39def37385b81ccbb2dea09ed4d3"

# Starting Block Information
starting_block_number: 2616250
starting_timestamp: 68668301
starting_blockhash: "a17a5299f0b1da59e22ee2dbf7b776ce8aa245080454824dd7416f67cbe6b17f"
delay_depth: 3

# Logging Parameters
max_log_file_size: "1 MB"
max_num_log_files: 1

# Available logging levels
# TRACE, DEBUG, INFO, SUCCESS, WARNING, ERROR, CRITICAL
logging_level: "TRACE"

# True is debug; False is no debug
debug_mode: False