###############################################################################
# This is the NEWM Market Batcher v1 config file. The data is split between
# hardcoded values that should not be changed and batcher specific values that
# need to be updated. Follow the README for detailed directions.
###############################################################################
#
###############################################################################
# Update Values For Your Batcher
###############################################################################
#
# Batcher Information
batcher_address: ""
profit_address: ""
#
# Collat Wallet Information
collat_address: ""
collat_utxo: ""
#
# Network Information
network: "--mainnet"
#
# Bin Paths; Need To be Absolute
aiken_path: "/bin/aiken"
addr_path: "/bin/cardano-address"
cli_path: "/bin/cardano-cli"
ogmios_path: "/bin/ogmios"
oura_path: "/bin/oura"
#
# Node File Paths; Needs To Be Absolute
node_config_path: "/config.json"
socket_path: "/node.socket"
#
# Node Port
node_port: 6000
#
# True Uses Ogmios For Tx Simulation; False Uses Aiken For Tx Simulation
use_ogmios: false
#
###############################################################################
# Do Not Update Values Below
###############################################################################
#
# Oracle Feed Information
oracle_address: "addr1wy32q7067yt9c2em8kx5us4vhxzv4xve24u6j8ptlc5mzqcahrwzt"
oracle_policy: "f155a26044efe91b3c44f87a7536d2d631c847717930ff547ae9d05c"
oracle_asset: "4f7261636c6546656564"
#
# Contract Addresses
sale_address: "addr1xxl4hgy86s5wsu9gp8p73ragmcqeuq047v2c9s8y409590wmwfzl7nlzxce79sgw7c3hfjntvnhasrf3lslhcscnsmsqyly5vr"
queue_address: "addr1x8752u4jpgwhde7up249fptehtxzkvv2fp320cf0jjm7wmwmwfzl7nlzxce79sgw7c3hfjntvnhasrf3lslhcscnsmsqfaf2sz"
vault_address: "addr1xxupj026ek9q564p7phdrq6kfz78dezccmzxy8z58dmf50kmwfzl7nlzxce79sgw7c3hfjntvnhasrf3lslhcscnsmsqx52z28"
band_address: "addr1xxlxwr74qmlrg0pr3wxrx463rwrrerppw06f5z6k4ws6kfxmwfzl7nlzxce79sgw7c3hfjntvnhasrf3lslhcscnsmsqxnq5u6"
#
# Data Contract Information
data_address: "addr1w978fpau5khes983pw0gywdea7jx7g8c0mwswhmc6c4thdcy423ez"
data_policy: "56cc98f6b22b063d71e6fe1af7cf2393dd698b5d84b1ecd33d0b3c08"
data_asset: "4e45574d61726b6574706c616365"
#
# Address Holding Script References UTxOs
reference_address: "addr1vyltjm9vmafv3p5epymnmf33waz0szyg9h9zv7mqn3z0s6q8e6thu"
#
# vault, Sale, and Queue Contract Script Reference UTxOs
sale_ref_utxo: "5e378ff057eb286ae6a883ae899080538a7ca5973c89b6fa45ce21e88fd470b4#1"
sale_lovelace: 22269770
#
queue_ref_utxo: "6536e1a888fbb6b1e890ba2e37cfe1d651c434de4fbd68ff1a2d8f4b6e2ed88a#1"
queue_lovelace: 30424290
#
vault_ref_utxo: "25c08f6b9acf8e5a0d1080eb5fc436510343ab7c6551e820164014dc1e485331#1"
vault_lovelace: 14998800
#
band_ref_utxo: "62b73c89279756de0afb15e04ed51d48d768817ee96bd6a05a4ee5e9ecd674c0#1"
band_lovelace: 20524220
#
batcher_ref_utxo: "7ad53e0048323f4e11b50f006f4b21f82acf284f38272d7ecae3a2984b7e9f2f#1"
batcher_lovelace: 7167530
#
# The Newm Pointer Policy Id
pointer_policy: "26c0f8e2d3be37de297fa57c48820fcb24c7b09aebe280430cef9d87"
#
# The Newm Batcher Policy Id
batcher_policy: "1cfcfe58e3462df9a3ab474a66536ef48f5acc2c1e7ad2abb294446a"
#
# Starting Block Information
starting_block_number: 10937312
starting_timestamp: 136847904
starting_blockhash: "a12247355c1b201e39acf9cf07dce6ef81cbb93ceeff0b669970332500808980"
delay_depth: 3
#
# Logging Parameters
max_log_file_size: "1 MB"
max_num_log_files: 1
#
# Available logging levels
#
# Options: TRACE, DEBUG, INFO, SUCCESS, WARNING, ERROR, CRITICAL
logging_level: "TRACE"
#
# True is debug; False is no debug
debug_mode: False
