###############################################################################
# This is the NEWM Market Batcher v1 config file. The data is split between
# hardcoded values that should not be changed and batcher specific values that
# need to be updated. Follow the README for detailed directions.
###############################################################################

###############################################################################
# Update Values For Your Batcher
###############################################################################

# Batcher Information
batcher_address: "addr_test1vrzfra0vdl6mkjyuenmxzr0302556w3dtyjachzukvdkpsqf4rq88"
profit_address: "addr_test1qrvnxkaylr4upwxfxctpxpcumj0fl6fdujdc72j8sgpraa9l4gu9er4t0w7udjvt2pqngddn6q4h8h3uv38p8p9cq82qav4lmp"

# Collat Wallet Information
collat_pkh: "4c1017ed05f703f6cf31c6a743f2c69534dbe4846e0d51ed4cb24b85"
collat_utxo: "949d496d900345508ed6e0b27b2a79a284fd3c37b7a3b7b01cece027fe1577aa#2"

# Node and network information
network: "--testnet-magic 1"
socket_path: "/home/logic/Documents/Work/LogicalMechanism/testnets/node-preprod/db-testnet/node.socket"

###############################################################################
# Do Not Update Values Below
###############################################################################

# Sale & Queue Contract Addresses
sale_address: "addr_test1xz0l8seu9tv265wu6gkajuarl62zz8uhq75u7gl9n6t8yuetr7epf7y6wzykrhezrfuptq7s4lgefz5m4a3cugsr8eyqej32nc"
queue_address: "addr_test1xrcxuuk0a46hnkxrzapcfkhlhaah4jzjnpc7yh9yahmc99etr7epf7y6wzykrhezrfuptq7s4lgefz5m4a3cugsr8eyq2r6j02"

# Data, Sale, and Queue Contract Script Reference UTxOs
data_ref_utxo: "f44798098faa85f69c57211b749358908c7ad47820bdb50230aae82c0eff3cd0#0"
sale_ref_utxo: "2b09daf2137c654fbfa7117d843c97126f47b9f0f7468bce06453d7ef5e1d92f#1"
queue_ref_utxo: "6cfc6a0b76567d5646a1408e3eae6dadbcf178ce62f71f22b399e08966e6973d#1"

# The newm pointer policy id
pointer_policy: "4e00b9275d13e901116778c495a4d621deb65062a24d3c1a4b91852f"

# The newm batcher policy id
batcher_policy: "aaf4e8d8ffaf5dc33a4a62ce62ac8876412b512a45c80d3aaa8b1a81"
batcher_asset: "5ca1ab1e000affab1e000ca11ab1e0005e77ab1e"

# starting block information
starting_block_number: 2289500
starting_timestamp: 61118858
starting_blockhash: "ff7a507a71db47aa0523a44682c584ab61e5e1a9bd448b3d5d0a4536e2806dbb"
delay_depth: 3

# Logging Parameters
max_log_file_size: "1 MB"
max_num_log_files: 1
logging_level: "TRACE"
