###############################################################################
# This is the NEWM Market Batcher v1 config file. The data is split between
# hardcoded values that should not be changed and batcher specific values that
# need to be updated. Follow the README for detailed directions.
###############################################################################

###############################################################################
# Update Values For Your Batcher
###############################################################################

# Batcher Information
batcher_address: ""
profit_address: ""

# Collat Wallet Information
collat_address: ""
collat_utxo: ""

# Network Information
#
# Options: --testnet-magic 1
# Options: --mainnet
network: "--mainnet"

# Bin Paths; Need To be Absolute
aiken_path: "/bin/aiken"
addr_path: "/bin/cardano-address"
cli_path: "/bin/cardano-cli"
ogmios_path: "/bin/ogmios"
oura_path: "/bin/oura"

# Node File Paths; Needs To Be Absolute
node_config_path: "/config.json"
socket_path: "/node.socket"

# Node Port
node_port: 6000

# True Uses Ogmios For Tx Simulation; False Uses Aiken For Tx Simulation
use_ogmios: False

# Docker - Not Supported - Do Not Use
# socket_path: "/root/node/node.socket"
# cli_path: "/root/bin/cardano-cli"

###############################################################################
# Do Not Update Values Below
###############################################################################

# Oracle Feed Information
oracle_address: "addr1wy32q7067yt9c2em8kx5us4vhxzv4xve24u6j8ptlc5mzqcahrwzt"
oracle_policy: "f155a26044efe91b3c44f87a7536d2d631c847717930ff547ae9d05c"
oracle_asset: "4f7261636c6546656564"

# Sale & Queue & Vault Contract Addresses
sale_address: ""
queue_address: ""
vault_address: ""

# Data Contract Information
data_address: ""
data_policy: ""
data_asset: ""

# Address Holding Script References UTxOs
reference_address: ""

# vault, Sale, and Queue Contract Script Reference UTxOs
sale_ref_utxo: "#1"
sale_lovelace: 0

queue_ref_utxo: "#1"
queue_lovelace: 0

vault_ref_utxo: "#1"
vault_lovelace: 0

# The Newm Pointer Policy Id
pointer_policy: ""

# The Newm Batcher Policy Id
batcher_policy: ""

# Starting Block Information
starting_block_number: 10848000
starting_timestamp: 135031945
starting_blockhash: "d303aa7bed199d968cb6675de6630289bbedc26b2b0dd3467404d6aec428266a"
delay_depth: 3

# Logging Parameters
max_log_file_size: "1 MB"
max_num_log_files: 1

# Available logging levels
#
# Options: TRACE, DEBUG, INFO, SUCCESS, WARNING, ERROR, CRITICAL
logging_level: "TRACE"

# True is debug; False is no debug
debug_mode: False