###############################################################################
# This is the NEWM Market Batcher v1 config file. The data is split between
# hardcoded values that should not be changed and batcher specific values that
# need to be updated. Follow the README for detailed directions.
###############################################################################

###############################################################################
# Update Values For Your Batcher
###############################################################################

# Batcher Information
batcher_address: "addr_test1vrs4fk7ea6rg2fvd00sa8um5unp0rt474kngwpc38v2z9vqujprdk"
profit_address: "addr_test1qrvnxkaylr4upwxfxctpxpcumj0fl6fdujdc72j8sgpraa9l4gu9er4t0w7udjvt2pqngddn6q4h8h3uv38p8p9cq82qav4lmp"

# Node and network information
network: "--testnet-magic 1"
socket_path: "/home/logic/Documents/Work/LogicalMechanism/testnets/node-preprod/db-testnet/node.socket"

###############################################################################
# Do Not Update Values Below
###############################################################################

# Sale & Queue Contract Addresses
sale_address: "addr_test1xrhsnzwtj24r6s496hprla9yucqf5vggr3kapm46fqnudewr6l77ugz28usv6qkcx0ra5g3jzjfdm04wrc6cr0ur6a6qau2un4"
queue_address: "addr_test1xq07nxps4vzj8mvcwhjpld54qcrkp8d73fextqdckdycefkr6l77ugz28usv6qkcx0ra5g3jzjfdm04wrc6cr0ur6a6qsgurj8"

# Data, Sale, and Queue Contract Script Reference UTxOs
data_ref_utxo: "79a63e963c9667dd5af80751dd86e5a720e8d47df3b772eb4a3e7c5fc7b6d017#0"
sale_ref_utxo: "411d8e9dcb895064b48a2257962c5c646dad5b66d3cd80822e0184e642c6695b#1"
queue_ref_utxo: "a9e7656a8b7a320917792013b720f8de3a1e9cb57bd382096d6f615fdb634eae#1"

# The newm pointer policy id
pointer_policy: "f24259627b32d494cd851d93a128410f2edeb1b3f407e935a0400da7"

# The newm batcher policy id
batcher_policy: "20053b53f8f381892dc2fe8a2562f6b4a2fe076143b7d9c6558c98f9"

# starting block information
starting_block_number: 2430000
starting_timestamp: 64348146
starting_blockhash: "bb3bf69eaf432900fe91a78827454ad1baf982b0c03b8071d60dc0b85a05981e"
delay_depth: 3

# Logging Parameters
max_log_file_size: "1 MB"
max_num_log_files: 1
logging_level: "TRACE"
