###############################################################################
# This is the NEWM Market Batcher v1 config file. The data is split between
# hardcoded values that should not be changed and batcher specific values that
# need to be updated. Follow the README for detailed directions.
###############################################################################

###############################################################################
# Update Values For Your Batcher
###############################################################################

# Batcher Information
batcher_address: "addr_test1vrs4fk7ea6rg2fvd00sa8um5unp0rt474kngwpc38v2z9vqujprdk"
profit_address: "addr_test1qrvnxkaylr4upwxfxctpxpcumj0fl6fdujdc72j8sgpraa9l4gu9er4t0w7udjvt2pqngddn6q4h8h3uv38p8p9cq82qav4lmp"

# Collat Wallet Information
collat_pkh: "c59da4ec6e515c2efc8866274dee6ac9a64b5945efd365f3a999e760"
collat_utxo: "1e0b413409dd9591b2a69bca80d7d776e8bb5130f02af0bf886e08ce5b6e183a#0"

# Node And Network Information
network: "--testnet-magic 1"
socket_path: "/home/logic/Documents/Work/LogicalMechanism/testnets/node-preprod/db-testnet/node.socket"

###############################################################################
# Do Not Update Values Below
###############################################################################

# Oracle Feed Address
oracle_address: "addr_test1wzc86g4ym366hkaphryqqvaptwznqkmk2gdqz9930u534pcx58ahw"
oracle_policy: "362e3f869c98ce971ead0e2705c56df467ddd2aecb44f6f216c3e1d5"
oracle_asset: "4f7261636c6546656564"

# Sale & Queue & Vault Contract Addresses
sale_address: "addr_test1xqk2zrw5g9pjk289kn8m8p68f254hnaacsmz3euwve3m5f8fe2gwsm4kjgam80dz22c4uvnad8zry884mqe0wjmpc75swa5eh0"
queue_address: "addr_test1xpg80nts44jr50utr23rxrz5jk02mfywudljszfengjl970fe2gwsm4kjgam80dz22c4uvnad8zry884mqe0wjmpc75szptqwc"
vault_address: "addr_test1xr66w6j86evtpxc29xgfc5uhetmmf4c0rvx73ad478473jlfe2gwsm4kjgam80dz22c4uvnad8zry884mqe0wjmpc75s7avfx7"

# Data Contract
data_address: "addr_test1wrp4cpyvutvy306n7xekpzfvysyls0d5nkzqel6agyfsh0ccwd96w"
data_policy: "9a3d3b5887f96b15faa7c2c42ebf46805587e7946345345b8a762667"
data_asset: "dba9b3fdc4ec5fddb8e3109393e44665c18231386433b8033db7092b794d1f39"

# Data, Sale, and Queue Contract Script Reference UTxOs
sale_ref_utxo: "402b8db50bdcc9db1355e4510435dd334964d549d43adb1490e24aaee5aa5a5d#1"
queue_ref_utxo: "27a3452545e4e4691fe397db7dbabace9d0bb54e07d80358113a6da60eb039a0#1"
vault_ref_utxo: "05b3d25ccbc9f3f298ef12b52411871bb45c518316d793e27cd9f20ceb5349c2#1"

# The Newm Pointer Policy Id
pointer_policy: "ed37d8a9be7f2e99db9d973731f63e9afc74b99b436e161390f907c5"

# The Newm Batcher Policy Id
batcher_policy: "d4add3a85c2ced3607ba0b17e71a403863c2435348bba0821f74523a"
batcher_asset: "5ca1ab1e000affab1e000ca11ab1e0005e77ab1e"

# Starting Block Information
starting_block_number: 2508424
starting_timestamp: 66180120
starting_blockhash: "afa362ac6a3a57f92dfee6f76bbe59b4f6e164385af4b82f0399009822d69f4e"
delay_depth: 3

# Logging Parameters
max_log_file_size: "1 MB"
max_num_log_files: 1
# Available logging levels
#
# TRACE, DEBUG, INFO, SUCCESS, WARNING, ERROR, CRITICAL
logging_level: "TRACE"

# Debug Mode
debug_mode: True