###############################################################################
# This is the NEWM Market Batcher v1 config file. The data is split between
# hardcoded values that should not be changed and batcher specific values that
# need to be updated. Follow the README for detailed directions.
###############################################################################

###############################################################################
# Update Values For Your Batcher
###############################################################################

# Batcher Information
batcher_address: "addr_test1vqzzzrr0tqft2dlxn47txnkvm9uvus70hade3cxk8m5pccsnespvn"
profit_address: "addr_test1qrvnxkaylr4upwxfxctpxpcumj0fl6fdujdc72j8sgpraa9l4gu9er4t0w7udjvt2pqngddn6q4h8h3uv38p8p9cq82qav4lmp"

# Collat Wallet Information
collat_address: "addr_test1vrt9kdej3je8tatg4ag35tmlrhej6c30wfluzl248fe5j7s29jsna"
collat_utxo: "e1504e1debcb78b456f19ac10d749c74e2b981d0cc965e4515188e92c8c59769#0"

# Node And Network Information
network: "--testnet-magic 1"
socket_path: "/home/logic/Documents/Work/LogicalMechanism/testnets/node-preprod/db-testnet/node.socket"

###############################################################################
# Do Not Update Values Below
###############################################################################

# Oracle Feed Address
oracle_address: "addr_test1wzc86g4ym366hkaphryqqvaptwznqkmk2gdqz9930u534pcx58ahw"
oracle_policy: "362e3f869c98ce971ead0e2705c56df467ddd2aecb44f6f216c3e1d5"
oracle_asset: "4f7261636c6546656564"

# Sale & Queue & Vault Contract Addresses
sale_address: "addr_test1xqac806wz4563gqwkcvrjx5ucls0zhr8eyjyqwptay5ljkg4nukc8gq26l6vx56r2xameewvj0kmqgszn4cegumc8d3qe2ty9j"
queue_address: "addr_test1xqyreluem3sxfvyjfuslpspxexewjl8r8r3xydn39laaj6q4nukc8gq26l6vx56r2xameewvj0kmqgszn4cegumc8d3qur55w7"
vault_address: "addr_test1xrwy3ylzjqvrshhfmh07w6wnm0hq23nrkjmyzlceqc3g5cc4nukc8gq26l6vx56r2xameewvj0kmqgszn4cegumc8d3q99p0qm"

# Data Contract
data_address: "addr_test1wze6szp52kupg2kcmwarqsqrntrqypwg94n77k4lm6eckts5yc34w"
data_policy: "8a29411b61d4d4fc79090ac49ca7c384420476adb523694f7f110ff6"
data_asset: "c65e8f235690f99453d7e02da594f2c180b3fe6af2236e676283fe61540e91eb"

# Data, Sale, and Queue Contract Script Reference UTxOs
reference_address: "addr_test1vzdhln27vnwxsz87htp8kynvxl62j0kygs8myk0a5qeu50sh5pfu7"

sale_ref_utxo: "9af67c86e6137d41915c0d0e554ad69ee86911c4c4d4f68fd0a2f4d384673ca9#1"
sale_lovelace: 41901820

queue_ref_utxo: "098a3281a90809d9ee1df32efb2570fce45dab43894e4509181a05cee8a23e18#1"
queue_lovelace: 57715210

vault_ref_utxo: "d784249b5093460ad0e3ae9e57d80c5651e3046c029f091fd980f0b997e6ddba#1"
vault_lovelace: 29570910

# The Newm Pointer Policy Id
pointer_policy: "2fb0decb35c05da7528b1871fee58f875c54b74f61e1a44f270d2115"

# The Newm Batcher Policy Id
batcher_policy: "32ede44e2939c30b7ee59eca6a680efdfc3510c4d63d0a197cb49257"

# Starting Block Information
starting_block_number: 2557028
starting_timestamp: 67293599
starting_blockhash: "02e52b1b2bd0462a05906b670b3cad63c1f03f3df81e04da0f7d034ad04acad1"
delay_depth: 3

# Logging Parameters
max_log_file_size: "1 MB"
max_num_log_files: 1

# Available logging levels
# TRACE, DEBUG, INFO, SUCCESS, WARNING, ERROR, CRITICAL
logging_level: "TRACE"

# Debug Mode; False is no debug
debug_mode: False