[source]
type = "N2C"
address = [ "Unix", "/home/logic/Documents/Work/LogicalMechanism/testnets/node-preprod/db-testnet/node.socket",]
magic = "preprod"
min_depth = 3

[sink]
type = "Webhook"
url = "http://localhost:8008/webhook"
timeout = 60000
error_policy = "Continue"

[source.intersect]
type = "Point"
value = [ 67411817, "b68258b1d5a0ca040f424bd2e4b4cafa0ec4997e23d0f5eeae909833205da0a7",]

[source.mapper]
include_block_end_events = true
include_transaction_details = true

[sink.retry_policy]
max_retries = 60
backoff_unit = 20000
backoff_factor = 2
max_backoff = 100000
