[source]
type = "N2C"
address = [ "Unix", "/home/logic/Documents/Work/LogicalMechanism/testnets/node-preprod/db-testnet/node.socket",]
magic = "preprod"
min_depth = 3

[sink]
type = "Webhook"
url = "http://localhost:8008/webhook"
timeout = 60000
error_policy = "Continue"

[source.intersect]
type = "Point"
value = [ 65563797, "f5ade7a4e6ce62ef170ea81513476c90d77482772d7cd98f5911fc5813f3472d",]

[source.mapper]
include_block_end_events = true
include_transaction_details = true

[sink.retry_policy]
max_retries = 60
backoff_unit = 20000
backoff_factor = 2
max_backoff = 100000
