[source]
type = "N2C"
address = [ "Unix", "/home/westbam/haskell/newmpp/db/socket",]
magic = "preprod"
min_depth = 3

[sink]
type = "Webhook"
url = "http://localhost:8008/webhook"
timeout = 60000
error_policy = "Continue"

[source.intersect]
type = "Point"
value = [ 71432318, "c06babd2e90af7c951d9fa864f135b5e8b66e867deeafe3261c7e3f4bd096a38",]

[source.mapper]
include_block_end_events = true
include_transaction_details = true

[sink.retry_policy]
max_retries = 60
backoff_unit = 20000
backoff_factor = 2
max_backoff = 100000
